### ISSUE TITLE
Clean up overlap between client properties and connection-parameters properties

### ISSUE THREAD

**Issue by DMickens** [vertica/vertica-nodejs#80]
There are a lot of properties for a node.js client. Many of these are new, specific to a Vertica connection. The connection properties really belong in the connection-parameters object within the client and not in both locations, which is messy. We need to decide which properties should be exposed in the Client and which should be in the connection-parameters. Whatever doesn't need exposed in the client, which may be all additional properties we have added.

Once this is done, anywhere that we need connection properties such as when creating a startup message, we need to update to take these from the client's connection-parameters.

**Comment by jonathanl-bq** [comment]
Resolved as Done.
