### ISSUE TITLE
Uncaught error: Invalid startup packet layout: expected terminator as last byte

### ISSUE THREAD

**Issue by Inxo** [vertica/vertica-nodejs#89]
I catch connection error 
`Uncaught error: Invalid startup packet layout: expected terminator as last byte`

Looks like need to modify startup handshake

My solution was add one more empty string to startup:
```
 var bodyBuffer = writer.addCString('').addCString('').flush()
```

nodejs: v16.13.2
vertica: v10.0.0-0

**Comment by DMickens** [comment]
Will look into this. We routinely test against the latest version of Vertica. There may have been an undocumented protocol change since 10.0.0

**Comment by nvish-dilpreetkaur** [comment]
@Inxo , I am also facing this issue which connecting to vertica database. How can I resolve this at my end?

**Comment by DMickens** [comment]
Causing regressions that weren't caught in CI automation. Will merge once we can verify it's only a test issue

**Comment by bcdan** [comment]
> I catch connection error `Uncaught error: Invalid startup packet layout: expected terminator as last byte`
> 
> Looks like need to modify startup handshake
> 
> My solution was add one more empty string to startup:
> 
> ```
>  var bodyBuffer = writer.addCString('').addCString('').flush()
> ```
> 
> nodejs: v16.13.2 vertica: v10.0.0-0

Also facing the exact thing.
Tried different versions of node.
Vertica version 10.1.1-17
Node versions I've tested - 19.4/16.19/14.21.2

**Comment by taiebmd** [comment]
I've the same issue on windows 10 (64x) +: NodeJs 19.3.0+ & Vertica 10.1+

**Comment by DMickens** [comment]
Confirmed that problem is seen with Vertica version 10.0 as noted in the issue, but not 12.0

**Comment by DMickens** [comment]
Resolved
